apiVersion: v1
kind: Service
metadata:
  name: ingress-lb
  namespace: sock-shop
spec:
  type: LoadBalancer
  selector:
    name: front-end
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
